fourthapp/urls.py
from django.urls import path
from fourthapp import views
app_name='fourthapp'

urlpatterns =[
    path('user_login/',views.user_login,name='log_in'),
    path('register/',views.register_user,name='register')
]

fourthproject/urls.py
from django.contrib import admin
from django.urls import path,include
from fourthapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('fourthapp/',include('fourthapp.urls')),
    path('logout/',views.log_out,name='logout'),
    path('special/',views.special,name='special')

]

fourthapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    userlink=models.EmailField(blank=True)
    user_image=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

fourthapp/forms.py
from django import forms
from django.contrib.auth.models import User
from fourthapp.models import ProfileInfo


class UserInfo(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','password','email')

class ProfileInfoForm(forms.ModelForm):
    class Meta():
        model=ProfileInfo
        fields=('userlink','user_image')

fourthapp/views.py
from django.shortcuts import render
from fourthapp.forms import ProfileInfoForm,UserInfo


from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'fourthapp/index.html')

def register_user(request):

    registered=False


    if request.method=='POST':
        user_info=UserInfo(data=request.POST)
        profile_info=ProfileInfoForm(data=request.POST)


        if user_info.is_valid() and profile_info.is_valid():
            user=user_info.save()
            user.set_password(user.password)
            user.save()

            profile=profile_info.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

                profile.save()
                registered=True

        else:
            print(user_info.errors,profile_info.errors)

    else:
        user_info=UserInfo()
        profile_info=ProfileInfoForm()

    return render(request,'fourthapp/register.html',{'profile_info':profile_info,
                                                     'user_info':user_info,
                                                     'registered':registered})


def user_login(request):

    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username='username',password='password')

        if user:
            if user.is_active:
                login(request,user)

                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('your account is not active')
        else:
            print('someone tried to log in')
            print('the username is: {} and password is: {}'.format(username,password))
            return HttpResponse('insert the correct details')

    else:
        return render(request,'fourthapp/log_in.html',{})

@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
@login_required
def special(request):
    return render(request,'fourthapp/special.html')

templates/fourthapp/base.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css"%}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'index'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'fourthapp:register'%}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'fourthapp:log_in'%}">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout'%}">Logout</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{%block body_block%}

{%endblock%}

  </body>
</html>

templates/fourthapp/index.html
<!DOCTYPE html>
{% extends 'fourthapp/base.html'%}

{%block body_block%}
<div class="jumbotron">
  <h1>Welcome!!Please Sign Up or Log In</h1>
</div>

{%endblock%}

templates/fourthapp/log_in.html
{%extends 'fourthapp/base.html'%}
{%block body_block%}

<form class="jumbotron" action="{%url 'special'%}" method="post">
  {%csrf_token%}
  <label for="username">Username</label>
  <input type="text" name="username" value="">
  <label for="password">Password</label>
  <input type="password" name="password" value="">
  <input type="submit" name="" value="Submit">

</form>
{%endblock%}

templates/fourthapp/register.html
{%extends 'fourthapp/base.html'%}

{% block body_block%}
<div class="jumbotron">
  <h1>Welcome To Boltem</h1>
  <h2>please log in or Sign Up</h2>

    {% if registered%}
    <h1>Thank you for regisstering</h1>
    {%else%}
    <form  method="POST" enctype="multipart/form-data">



    {%csrf_token%}

    {{user_info.as_p}}
    {{profile_info.as_p}}
    <input type="submit" value="Submit">
  </form>
    {%endif%}



</div>


{%endblock %}

templates/fourthapp/special.html
{%extends 'fourthapp/base.html'%}
{% block body_block%}

<div class="jumbotron">
  <h1>Thank you for Registering,you are  logged in</h1>

</div>
{%endblock%}